### ISSUE TITLE
Data source test OK. Can't display any data

### ISSUE THREAD

**Issue by cjt74392** [Crinon/grafana-riverbed-appresponse#12]
Add Data source error,  

with error "process is not defined evaluating"

How can I fix this ?

**Comment by Crinon** [comment]
Hello,
I'm not able to use this plugin anymore, so I can only use my memory to help you.
Can you try to acces NetIM API through insomnia / postman ?

**Comment by cjt74392** [comment]
Hi Crinon:
Thanks for your reply.

I asked the wrong question earlier. 
Actually I installed grafana-riverbed-appresponse. not NetIM

I follow document 
Download, unzip and place the grafana-riverbed-appresponse folder in the plugins directory /var/lib/grafana/plugins
When I try to create data source, the erro happen. "process is not defined"
![image](https://user-images.githubusercontent.com/2269156/119448046-5fb45d80-bd63-11eb-8ed2-4307206bc18d.png)

I try to modify grafana-riverbed-appresponse/dist/datasource.js 
correct globalHOST、 "username":  "password" 、uri， but no help.

I believe your memory should be very good to help me out.

**Comment by cjt74392** [comment]
1.Add datasource -->click select
![image](https://user-images.githubusercontent.com/2269156/119663631-1815fa80-be65-11eb-8c0f-e7fc25ccf588.png)

2.Then error appear
![image](https://user-images.githubusercontent.com/2269156/119663806-4c89b680-be65-11eb-8d30-7cd715894084.png)

**Comment by Crinon** [comment]
I have to ask the silly question : Did you reboot your Grafana server ?
Grafana scans the plugin directory at start (but I assume you did because you can select AppResponse as datasource, but honestly I don't know why you can't add properly the datasource)

**Comment by cjt74392** [comment]
Hi~

I have to ask the silly question : Did you reboot your Grafana server ?
A: Sure, If not I can't see the data source plugin

Grafana scans the plugin directory at start (but I assume you did because you can select AppResponse as datasource, but honestly I don't know why you can't add properly the datasource)
A:Wlould you mind to  add this native datasource on your grafana server ? you can reproduce this problem without setting

**Comment by Crinon** [comment]
I'm not on Grafana server for the moment, I'm thiking about another thing, I developped it a year and a half ago, it was on older version of Grafana, and my team migrated on last build recently whithout me, maybe they encountered this issue (they did not ask me for help so I can't say)

Maybe it can come from the UNSIGNED warning, I never saw it during development

I do not declare any process variable in my plugin, so that should be a grafana core variable

**Comment by cjt74392** [comment]
After  npm rebuild, It's work now, but still have problem "Query error: 404 Not found"
![image](https://user-images.githubusercontent.com/2269156/119762610-9bc0fd00-bee0-11eb-9eff-ad6f85e08a9f.png)

"Query error: 404 Not found"
![image](https://user-images.githubusercontent.com/2269156/119762648-ab404600-bee0-11eb-9d1e-25fd5a71bc3b.png)

I need your help again

**Comment by Crinon** [comment]
Use dev tools and find the URL used by the plugin to get data
For example I declare hostgroup's endpoint :     '/api/npm.classification/2.0/hostgroups';

**Comment by cjt74392** [comment]
Hi Crinon:
I use postman try to get data
1.First, get token
![image](https://user-images.githubusercontent.com/2269156/119857845-7d8de800-bf46-11eb-9fd3-a908ee41a44f.png)

2.Use token with endpoint : '/api/npm.classification/2.0/hostgroups'; to get data
get error code: Forbidden
![image](https://user-images.githubusercontent.com/2269156/119857297-05bfbd80-bf46-11eb-8963-1056d7ef3b04.png)

 Is that mean SteelCentral Portal user account with no authority to get data, 
SteelCentral Portal web USER need which kind of authority ?

**Comment by Crinon** [comment]
Forbidden is not unauthaurized, you need an account for AppResponse, it is not the same account
Try with a real AppResponse account

**Comment by cjt74392** [comment]
Hi Crinon:
Solved the problem. 
Thanks for you help.
